<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="robot">

    <xacro:property name="chassis_length" value="0.4"/>
    <xacro:property name="chassis_width" value="0.3"/>
    <xacro:property name="chassis_height" value="0.1"/>
    <xacro:property name="wheel_radius" value="0.05"/>
    <xacro:property name="wheel_width" value="0.04"/>
    <xacro:property name="wheel_separation" value="0.35"/>
    <xacro:property name="wheel_offset_x" value="0.15"/>

    <!-- Base Link -->
    <link name="base_link">
    </link>

    <!-- Chassis -->
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="-0.1 0 0"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="blue">
                <color rgba="0 0 1 1"/>
            </material>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <mass value="1.0"/>
            <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
        </inertial>
    </link>

    <!-- Wheels -->
    <xacro:macro name="wheel" params="name x y">
        <link name="${name}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <material name="black">
                    <color rgba="0 0 0 1"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="0.1"/>
                <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
            </inertial>
        </link>

        <joint name="${name}_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${name}_wheel"/>
            <origin xyz="${x} ${y} 0" rpy="${-pi/2} 0 0"/>
            <axis xyz="0 0 1"/>
        </joint>
    </xacro:macro>

    <!-- Rear Wheels (Driven) -->
    <xacro:wheel name="left_rear" x="0" y="${wheel_separation/2}"/>
    <xacro:wheel name="right_rear" x="0" y="${-wheel_separation/2}"/>

    <!-- Front Wheels (Caster-like, simplified as sliding wheels for diff drive stability or just spheres) -->
    <!-- For a 4-wheeled car look, we use cylinders but set friction low or use a caster joint. 
         To keep it simple for diff drive, let's use a caster wheel in the front. 
         But user asked for 4 wheels. Let's make 2 passive front wheels. -->
    <xacro:wheel name="left_front" x="${chassis_length-0.1}" y="${wheel_separation/2}"/>
    <xacro:wheel name="right_front" x="${chassis_length-0.1}" y="${-wheel_separation/2}"/>

    <!-- IMU Sensor -->
    <joint name="imu_joint" type="fixed">
        <parent link="chassis"/>
        <child link="imu_link"/>
        <origin xyz="${chassis_length/2} 0 ${chassis_height}" rpy="0 0 0"/>
    </joint>

    <link name="imu_link">
        <visual>
            <geometry>
                <box size="0.05 0.05 0.02"/>
            </geometry>
            <material name="red">
                <color rgba="1 0 0 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="0.05 0.05 0.02"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.01"/>
            <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
        </inertial>
    </link>


    <!-- Gazebo Plugins for Ignition Fortress -->
    
    <!-- Diff Drive Plugin -->
    <gazebo>
        <plugin filename="libignition-gazebo-diff-drive-system.so" name="ignition::gazebo::systems::DiffDrive">
            <left_joint>left_rear_wheel_joint</left_joint>
            <right_joint>right_rear_wheel_joint</right_joint>
            <wheel_separation>${wheel_separation}</wheel_separation>
            <wheel_radius>${wheel_radius}</wheel_radius>
            <odom_publish_frequency>20</odom_publish_frequency>
            <topic>cmd_vel</topic>
            <odom_topic>odom</odom_topic>
            <tf_topic>tf</tf_topic>
            <frame_id>odom</frame_id>
            <child_frame_id>base_link</child_frame_id>
        </plugin>
    </gazebo>

    <!-- IMU Plugin -->
    <gazebo reference="imu_link">
        <sensor name="imu_sensor" type="imu">
            <always_on>1</always_on>
            <update_rate>20</update_rate>
            <visualize>true</visualize>
            <topic>imu</topic>
        </sensor>
    </gazebo>
    
    <!-- We also need the IMU system plugin, but often it's loaded by default or in world. 
         However, adding it to the model ensures it works. -->
    <gazebo>
        <plugin filename="libignition-gazebo-imu-system.so" name="ignition::gazebo::systems::Imu">
        </plugin>
    </gazebo>

    <!-- Joint State Publisher -->
    <gazebo>
        <plugin filename="libignition-gazebo-joint-state-publisher-system.so" name="ignition::gazebo::systems::JointStatePublisher">
            <topic>joint_states</topic>
        </plugin>
    </gazebo>

    <!-- Friction for wheels -->
    <gazebo reference="left_rear_wheel">
        <mu1>1.0</mu1>
        <mu2>1.0</mu2>
    </gazebo>
    <gazebo reference="right_rear_wheel">
        <mu1>1.0</mu1>
        <mu2>1.0</mu2>
    </gazebo>
    <!-- Low friction for front wheels to allow turning (skid-like behavior) -->
    <gazebo reference="left_front_wheel">
        <mu1>0.01</mu1>
        <mu2>0.01</mu2>
    </gazebo>
    <gazebo reference="right_front_wheel">
        <mu1>0.01</mu1>
        <mu2>0.01</mu2>
    </gazebo>

</robot>
