<?xml version="1.0"?>
<robot name="four_wheel_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- 定义机器人参数 -->
  <xacro:property name="M_PI" value="3.1415926535897931" />

  <!-- 车身参数 -->
  <xacro:property name="chassis_length" value="0.4" />
  <xacro:property name="chassis_width" value="0.2" />
  <xacro:property name="chassis_height" value="0.1" />
  <xacro:property name="chassis_mass" value="2.0" />

  <!-- 轮子参数 -->
  <xacro:property name="wheel_radius" value="0.05" />
  <xacro:property name="wheel_width" value="0.02" />
  <xacro:property name="wheel_mass" value="0.5" />

  <!-- 轮子位置参数 -->
  <xacro:property name="wheelbase" value="0.3" />  <!-- 前后轮距 -->
  <xacro:property name="track_width" value="0.15" /> <!-- 左右轮距 -->

  <!-- 材料定义 -->
  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>
  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>

  <!-- 车身连杆 -->
  <link name="chassis">
    <visual>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${chassis_mass}"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
  </link>

  <!-- 轮子宏定义 -->
  <xacro:macro name="wheel" params="prefix x y z">
    <link name="${prefix}_wheel">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black"/>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
      </collision>
      <inertial>
        <mass value="${wheel_mass}"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
      </inertial>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="chassis"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>

    <!-- Gazebo轮子插件 -->
    <gazebo reference="${prefix}_wheel">
      <mu1 value="1.0"/>
      <mu2 value="1.0"/>
      <kp value="10000000.0" />
      <kd value="1.0" />
      <fdir1 value="1 0 0"/>
    </gazebo>

    <!-- 传输 -->
    <transmission name="${prefix}_wheel_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}_wheel_joint">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
      <actuator name="${prefix}_wheel_motor">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>

  <!-- 创建四个轮子 -->
  <xacro:wheel prefix="front_left" 
               x="${wheelbase/2}" y="${track_width/2}" z="0"/>
  <xacro:wheel prefix="front_right" 
               x="${wheelbase/2}" y="${-track_width/2}" z="0"/>
  <xacro:wheel prefix="back_left" 
               x="${-wheelbase/2}" y="${track_width/2}" z="0"/>
  <xacro:wheel prefix="back_right" 
               x="${-wheelbase/2}" y="${-track_width/2}" z="0"/>

  <!-- Gazebo插件 -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/four_wheel_bot</robotNamespace>
    </plugin>
  </gazebo>

  <!-- 差分驱动插件 -->
  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <robotNamespace>/four_wheel_bot</robotNamespace>
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <robotBaseFrame>chassis</robotBaseFrame>
      <publishOdometry>true</publishOdometry>
      <publishWheelTF>true</publishWheelTF>
      <publishOdomTF>true</publishOdomTF>
      <legacyMode>false</legacyMode>
      
      <!-- 轮子关节配置 -->
      <leftJoint>front_left_wheel_joint</leftJoint>
      <leftJoint>back_left_wheel_joint</leftJoint>
      <rightJoint>front_right_wheel_joint</rightJoint>
      <rightJoint>back_right_wheel_joint</rightJoint>
      
      <!-- 轮子尺寸和间距 -->
      <wheelSeparation>${track_width}</wheelSeparation>
      <wheelDiameter>${2*wheel_radius}</wheelDiameter>
      
      <!-- 控制参数 -->
      <torque>10</torque>
      <updateRate>30</updateRate>
    </plugin>
  </gazebo>

</robot>