<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="four_wheel_robot">
  <xacro:property name="wheel_radius" value="0.08"/>
  <xacro:property name="wheel_width" value="0.04"/>
  <xacro:property name="base_length" value="0.4"/>
  <xacro:property name="base_width" value="0.3"/>
  <xacro:property name="base_height" value="0.12"/>
  <xacro:property name="wheel_offset_x" value="${base_length / 2.0 - wheel_width / 2.0}"/>
  <xacro:property name="wheel_offset_y" value="${base_width / 2.0 - wheel_radius}"/>

  <link name="base_link">
    <inertial>
      <mass value="8.0"/>
      <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
      <inertia ixx="0.12" ixy="0.0" ixz="0.0" iyy="0.15" iyz="0.0" izz="0.20"/>
    </inertial>
    <visual>
      <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="blue">
        <color rgba="0.1 0.3 0.8 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
  </link>

  <xacro:macro name="wheel" params="prefix x y">
    <link name="${prefix}_wheel_link">
      <inertial>
        <mass value="1.0"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.002" ixy="0" ixz="0" iyy="0.004" iyz="0" izz="0.002"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black">
          <color rgba="0.05 0.05 0.05 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <origin xyz="${x} ${y} ${wheel_radius}" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="${prefix}_wheel_link"/>
      <axis xyz="0 1 0"/>
      <limit effort="10.0" velocity="30.0"/>
      <dynamics damping="0.1" friction="0.0"/>
    </joint>

    <gazebo reference="${prefix}_wheel_link">
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
      <kp>100000.0</kp>
      <kd>10.0</kd>
      <fdir1>1 0 0</fdir1>
    </gazebo>
  </xacro:macro>

  <xacro:wheel prefix="front_left" x="${wheel_offset_x}" y="${wheel_offset_y}"/>
  <xacro:wheel prefix="front_right" x="${wheel_offset_x}" y="${-wheel_offset_y}"/>
  <xacro:wheel prefix="rear_left" x="${-wheel_offset_x}" y="${wheel_offset_y}"/>
  <xacro:wheel prefix="rear_right" x="${-wheel_offset_x}" y="${-wheel_offset_y}"/>

  <transmission name="front_left_wheel_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="front_left_wheel_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="front_left_wheel_motor">
      <mechanicalReduction>1</mechanicalReduction>
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </actuator>
  </transmission>
  <transmission name="front_right_wheel_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="front_right_wheel_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="front_right_wheel_motor">
      <mechanicalReduction>1</mechanicalReduction>
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </actuator>
  </transmission>
  <transmission name="rear_left_wheel_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="rear_left_wheel_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="rear_left_wheel_motor">
      <mechanicalReduction>1</mechanicalReduction>
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </actuator>
  </transmission>
  <transmission name="rear_right_wheel_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="rear_right_wheel_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="rear_right_wheel_motor">
      <mechanicalReduction>1</mechanicalReduction>
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </actuator>
  </transmission>
  <gazebo>
    <plugin name="ros2_control" filename="libignition_ros2_control-system.so">
      <parameters>$(find four_wheel_robot)/config/ros2_control.yaml</parameters>
    </plugin>
  </gazebo>

  <ros2_control name="four_wheel_robot_system" type="system">
    <hardware>
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware>
    <joint name="front_left_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="front_right_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="rear_left_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="rear_right_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>
</robot>
